In [1]:
import numpy as np

In [6]:
a=np.array([1,2,3,4])
print (a)

[1 2 3 4]


In [7]:
import numpy as np

In [8]:
a=np.array([[1,2,3,4],[3,4,5,6],[9,7,5,3],[3,5,6,7]])
print(a)

[[1 2 3 4]
 [3 4 5 6]
 [9 7 5 3]
 [3 5 6 7]]


In [9]:
import numpy as np

In [14]:
a=np.array([1,2,3,4,5,6], ndmin=3)
print(a)

[[[1 2 3 4 5 6]]]


In [15]:
import numpy as np

In [20]:
a=np.array([1,2,3,4], dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [21]:
import numpy as np

In [24]:
a=np.dtype(np.int64)
print(a)

int64


In [25]:
import numpy as np

In [28]:
dt=np.dtype('i4')
print(dt)

int32


In [29]:
dt=np.dtype('i1')
print(dt)

int8


In [30]:
dt=np.dtype('i8')
print(dt)

int64


In [31]:
import numpy as np

In [37]:
a=np.dtype([('age', np.int8)])
print(a)

[('age', 'i1')]


In [35]:
import numpy as np
dt = np.dtype([('age',np.int8)])
a = np.array([(10,),(20,),(30,)], dtype=dt)
print (a)

[(10,) (20,) (30,)]


In [36]:
import numpy as np
dt = np.dtype([('age',np.int8)])
print (dt)

[('age', 'i1')]


In [38]:
import numpy as np

In [42]:
dt=np.dtype([('age',np.int8)])
a=np.array([(10),(20),(30)],dtype=dt)
print(a)

[(10,) (20,) (30,)]


In [43]:
import numpy as np

In [46]:
a=np.dtype([('name','S20'),('age','i1'),('marks','f4')])
print(a)

[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]


In [47]:
import numpy as np

In [49]:
a=np.array([[1,2,3],[4,5,6]])
a.shape

(2, 3)

In [50]:
a=np.array([[1,2,3,4,5,6],[4,5,6,7,8,9],[4,5,6,7,8,1]])
a.shape

(3, 6)

In [58]:
a=np.array([[1,2,3,4],[4,5,6,7]])
a.shape

(2, 4)

In [61]:
a.shape=(4,2)

In [62]:
print (a)

[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [63]:
import numpy as np

In [65]:
a=np.arange(100000000)
print(a)

[       0        1        2 ... 99999997 99999998 99999999]


In [66]:
import numpy as np

In [69]:
a=np.arange(24)
a.ndim
b=a.reshape(2,4,3)
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [70]:
import numpy as np

In [75]:
a=np.array([3,4,5,6,7])
print(a.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


In [76]:
import numpy as np

In [77]:
a=np.empty([3,2],dtype= int)
print(a)

[[       0        1]
 [       2 99999997]
 [99999998 99999999]]


In [81]:
import numpy as np
x = np.empty([3,2], dtype=int)
print (x)

[[1 2]
 [3 4]
 [5 6]]


In [82]:
import numpy as np

In [83]:
a=np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [85]:
a=np.zeros((5,),dtype=np.int)
print(a)

[0 0 0 0 0]


In [86]:
a=np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [87]:
a=np.ones((5),dtype=np.int)
print(a)

[1 1 1 1 1]


In [88]:
a=[1,2,3,4]
x=np.asarray(a)
print(x)

[1 2 3 4]


In [90]:
a=[2,3,4,5,6]
x=np.asarray(a, dtype=float)
print(x)

[2. 3. 4. 5. 6.]


In [93]:
a='ankur singh'
x=np.frombuffer(a, dtype='S1')
print(x)

AttributeError: 'str' object has no attribute '__buffer__'

In [95]:
import numpy as np
s = 'Hello World'
a = np.frombuffer(s, dtype='S1')
print (a)

AttributeError: 'str' object has no attribute '__buffer__'