numpy fullfrom # numerical python, it is use for only array and matrices

In [2]:
a=np.array([5,6,7])
a[0]

5

In [3]:
b=np.array([[1,2],[3,4],[5,6]])

In [4]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
b.ndim

2

In [7]:
a=np.arange(1,10).reshape(3,3)

In [13]:
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
a.ndim

2

for dimension find

In [17]:
a.itemsize   #those element belong to take space 4 byte

4

In [18]:
a.dtype

dtype('int32')

In [19]:
a.shape

(3, 3)

In [21]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
c=np.ones((3,4))

In [23]:
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
d=np.arange(5)

In [26]:
d

array([0, 1, 2, 3, 4])

In [27]:
d=np.linspace(1,5,10)   # ager mere pass (1,5)  array hai isko 10 part me todta hai

In [28]:
d

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [29]:
d.shape

(10,)

In [32]:
a=np.arange(0,9).reshape(3,3)

In [33]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
a.ravel()  # kisi bhi shape chahe (2,5 ka or koi ho isko break ker k ek array me ker deta hai)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
a.min()

0

In [39]:
a.max()

8

In [44]:
a=np.arange(0,9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
a.sum()

36

In [46]:
a.sum(axis=0)     # coloum ko add ker k output de rha hai

array([ 9, 12, 15])

In [47]:
a.sum(axis=1)    # row ko add ker k output de rha hai

array([ 3, 12, 21])

In [49]:
np.sqrt(a)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])

# class 2 (less memory& fast)

In [50]:
a=np.array([1,2,3])

In [51]:
a

array([1, 2, 3])

In [52]:
import numpy as np
import time
import sys       ## system me se kaise data lete hai

In [54]:
l=range(1000)
l

range(0, 1000)

In [57]:
print(sys.getsizeof(700)*len(l))  # 700 k jagah koi rakh skte ho (o,se 1000 )tk

28000


In [59]:

array=np.arange(1000)
print(array.size*array.itemsize)   # memory consuming numpy is less memory consume

4000


In [62]:
import numpy as np
import time
size=1000000
l1=range(size)
l2=range(size)

In [69]:
a1=np.arange(size)
a2=np.arange(size)
   # python list
start=time.time()
result=[x+y for x,y in zip(l1,l2)]
print("python list took:",(time.time()-(start))*1000)

python list took: 267.98295974731445


In [70]:
# python array
start=time.time()
result=a1+a2
print("python array took :",(time.time()-start)*1000)

python array took : 30.896663665771484


In [71]:
a1=np.array([4,5,6])
a2=np.array([1,2,3])
a1-a2

array([3, 3, 3])

In [72]:
a1+a2

array([5, 7, 9])

In [75]:
a=np.arange(0,9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [76]:
a[:,0]

array([0, 3, 6])

In [78]:
a[-1]

array([6, 7, 8])

In [80]:
for row in a:
    print(row)

[0 1 2]
[3 4 5]
[6 7 8]


In [81]:
a.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [83]:
for i in a.flatten():
    print(i)

0
1
2
3
4
5
6
7
8


In [85]:
a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)

In [86]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [87]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [88]:
np.vstack((a,b)) # v means verticle

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [89]:
a=np.hstack((a,b))    # h means horizantal

In [90]:
a

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [93]:
d=np.hsplit(a,2)

In [95]:
d[0]

array([[0, 1],
       [2, 3],
       [4, 5]])

In [96]:
d[1]

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [97]:
e=a>0
e

array([[False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [98]:
a

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [99]:
a[e]   # e me jo value true hogi vo output de degi

array([ 1,  6,  7,  2,  3,  8,  9,  4,  5, 10, 11])

# class 4 (iterator)

In [100]:
import numpy as np
p=np.arange(12).reshape(3,4)
p

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [101]:
for row in p:
    for i in row:
        print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [102]:
for j in p.flatten():
    print(j)

0
1
2
3
4
5
6
7
8
9
10
11


In [105]:
for x in np.nditer(p,order='A'):  # u can use A,B,C,F
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [106]:
for x,y in np.nditer([p,b]):
    print(x,y)

ValueError: operands could not be broadcast together with shapes (3,4) (3,2) 